camera modal stores data to backend, removed on tag close
ctc-uci/stand-up-to-trash-frontend pull request #104
Opened 2024-03-01 04:21 UTC by stevem-zhou

Authors: @tig-github   @stevem-zhou 
 ### What does this PR contain?
Created camera modal, image routes, item tags

 ### How did you test these changes?
Took pictures, deleted tags, 100x checked database each time

 ### Attach images (if applicable)

closes #101

2024-03-01 20:41 UTC, Aokijiop requested changes
After making some small adjustments to the backend routes, the functionality is working good in `Playground`. 

However there is some missing functionality:
- `DataEntryModal` hasn't been updated to conditionally render the `ImageTag` component
- The tables event_data_new and event_data_images shouldn't be updated with the newly added images until the user submits in the `DataEntryModal` (I reread the issue and that was my bad since I said "when a picture is taken")
    - Basically ensure that if the user were to exit out of `DataEntryModal` without submitting, the newly added images won't appear in the table 
    - If you need more time then until Sunday to fix this, please let me know because this was also my bad with the wording
- When an `ImageTag` is clicked, it should open a modal that displays the stored image

2024-03-02 19:30 UTC, ctc-devops commented on src/components/DataEntryModal/DataEntryModal.jsx
> +  }, []);
⚠️ **[eslint]** <[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>React Hook useEffect has a missing dependency: 'id'. Either include it or remove the dependency array.

2024-03-02 19:40 UTC, ctc-devops commented on src/components/DataEntryModal/DataEntryModal.jsx
> +  }, []);
⚠️ **[eslint]** <[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>React Hook useEffect has a missing dependency: 'id'. Either include it or remove the dependency array.

2024-03-04 02:55 UTC, Aokijiop approved these changes
Looks good! Just a couple things that needed to be changed:
- When deleting an item, make sure to also remove it from uploadedImages (In the event that we take a picture and then delete then submit all within one submission)
- Upon submission, we also need to reset uploadedImages so that we don't keep repeatedly uploading the same images over and over again

2024-03-04 02:56 UTC, merged